receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:

exporters:
  file:
    path: /data/otel/log.jsonl
    format: json
  file/metric:
    path: /data/otel/metric.jsonl
    format: json
  file/trace:
    path: /data/otel/trace.jsonl
    format: json
  otlphttp:
    endpoint: http://loki:3100/otlp
  prometheus:
    endpoint: 0.0.0.0:8889
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [ health_check, pprof, zpages ]
  pipelines:
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ file, otlphttp ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ file/metric, prometheus ]
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ file/trace, zipkin ]