# Spring properties
spring:
  application:
    name: order-service
  threads:
    virtual:
      enabled: true

# OpenTelemetry config
otel:
  instrumentation:
    micrometer:
      enabled: true
# Logging config
logging:
  level:
    root: INFO

# Actuator config
management:
  endpoints:
    web:
      exposure:
        include: health, metrics
  tracing:
    sampling:
      probability: 1.0
  otlp:
    logging:
      export:
        enabled: true
      transport: http
      endpoint: "http://localhost:4318/v1/logs"
    metrics:
      export:
        enabled: true
        step: 15s
        url: "http://localhost:4318/v1/metrics"
    tracing:
      export:
        enabled: true
      transport: grpc
      endpoint: "0.0.0.0:4317"
