# Spring properties
spring:
  application:
    name: order-service
  threads:
    virtual:
      enabled: true

# OpenTelemetry config
otel:
  instrumentation:
    micrometer:
      enabled: true
  exporter:
    otlp:
      logs:
        endpoint: "http://localhost:4318/v1/logs"
        protocol: http/protobuf
      metrics:
        endpoint: "http://localhost:4318/v1/metrics"
        protocol: http/protobuf
      traces:
        endpoint: "http://localhost:4317"
        protocol: grpc
# Logging config
logging:
  level:
    root: INFO
# Actuator config
management:
  observations:
    annotations:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, metrics
