# Spring properties
spring:
  application:
    name: order-service
  threads:
    virtual:
      enabled: true

# OpenTelemetry config
otel:
  instrumentation:
    micrometer:
      enabled: true
    logback-appender:
      experimental-log-attributes: true
      experimental:
        capture-mdc-attributes: "*"
# Logging config
logging:
  level:
    root: INFO

# Actuator config
management:
  endpoints:
    web:
      exposure:
        include: health, metrics
  otlp:
    logging:
      export:
        enabled: true
      transport: http
      endpoint: "http://localhost:4318/v1/logs"
    metrics:
      export:
        enabled: true
        step: 1s
        url: "http://localhost:4318/v1/metrics"
    tracing:
      export:
        enabled: true
      transport: http
      endpoint: "http://localhost:4318/v1/traces"
