receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:

exporters:
  otlphttp:
    endpoint: http://loki:3100/otlp
  file:
    path: /data/otel/otel-data.jsonl
    format: json
  prometheus:
    endpoint: 0.0.0.0:8889
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [ health_check, pprof, zpages ]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ file, zipkin ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ file, prometheus ]
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlphttp ]